### PR TITLE
Calendar v2

### PR DESCRIPTION
**Pull request by okzea**
Ticket: https://bookingsync.atlassian.net/browse/PRO-3077

Demo: https://widgets-demo.happystay.com/en?variant=calendar&currency=EUR&debug=1

Changes:
    - cancel selection when clicking on the first selected date
    - select in both direction (currently only from left to right)
    - show tooltip if selection is not valid (minstay or booked)
    - invalid selection stays highlighted until you select new dates
    - hover handler moved to JS (to be able to select cell's previous sibling)

### CODE REVIEW

**Review by abel-n — COMMENTED** [review]
@okzea it seems like selection isn't allowed to start right after another booking ended, is that intended?
https://a.cl.ly/E0ujjzpQ

**Comment by okzea** [comment]
@abel-n no it's not intended 😅

**Review by abel-n — APPROVED** [review]
Code looks good to me, though I'm not saying I comprehend all lines of the code base.

Maybe one thing, I'm not sure what are the rules for color of days but if it's "available dates are darker, unavailable lighter", then probably the encircled days in the image below should be darker.
calendar-widget-start-end-color

**Comment by okzea** [comment]
@abel-n this particular example is to showcase the use of CSS vars with dummy colors, as default we use those 
image

**Comment by okzea** [comment]
tested and approved by Yannick (product side)

**Comment by abel-n** [comment]
@okzea Still, there are two kinds of day colors if I'm correct, and although they are set to be the same in the example you just shared, they _could_ be different and as such it should follow the guide lines consistently. Problem is, I don't know what the guide lines are :joy: Also in Ember calendars we use a bit shifted "booking pillars", so there is no such issue there:
admin-ui-calendar-days-design

**Comment by abel-n** [comment]
Haha I see my comment arrived a bit late :joy:

**Comment by okzea** [comment]
@abel-n I've just compared with a very old version, it has the normal color on the left and right side, I guess it got lost on the way 😅, I'll push a fix
image

**Comment by okzea** [comment]
fixed in https://github.com/BookingSync/calendar-widget/pull/99

**Pull request merged**
